
/**:
  ros__parameters:
    wheel_radius: 0.1825
    wheel_width: 0.145
    wheel_base: 0.44 # between front wheel center and rear wheel center
    wheel_tread: 0.697 # between left wheel center and right wheel center
    front_overhang: 0.0 # between front wheel center and vehicle front
    rear_overhang: 0.0 # between rear wheel center and vehicle rear
    left_overhang: 0.0 # between left wheel center and vehicle left
    right_overhang: 0.0 # between right wheel center and vehicle right
    vehicle_height: 0.365
    max_steer_angle: 0.70 # [rad]